import Link from "next/link";
import { ArrowLeft } from "lucide-react";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms and Conditions | Flycomm",
  description: "Flycomm Networks App Terms and Conditions for use of the platform and services.",
};

export default function TermsPage() {
  return (
    <article className="min-h-screen">
      <div className="max-w-4xl mx-auto px-6 md:px-12 pt-32 pb-20">
        <Link
          href="/"
          className="inline-flex items-center gap-1.5 text-sm text-text-muted hover:text-brand transition-colors mb-8"
        >
          <ArrowLeft className="h-3.5 w-3.5" /> Back to Home
        </Link>

        <h1 className="text-3xl md:text-4xl font-bold font-[family-name:var(--font-space-grotesk)] mb-3">
          Terms and Conditions
        </h1>
        <p className="text-text-muted text-sm mb-10">Flycomm Networks App &middot; Last Updated &mdash; March 2025</p>

        <div className="legal-content space-y-6">
          <p>
            These Terms and Conditions (&quot;Terms and Conditions&quot;) are a legally binding agreement between you, the person or entity that will be accessing or using Company&apos;s online platform (referenced below as &quot;Customer&quot;), and Flycomm Networks Ltd. (the &quot;Company&quot;), with respect to the use of the Company&apos;s online platform available to Customer by Company (the &quot;Platform&quot;). Company and Customer may also be referred to individually as a &quot;Party&quot; and collectively as the &quot;Parties&quot;.
          </p>
          <p>
            By using the Company&apos;s Platform, Customer accepts these Terms and Conditions. The Company reserves the right, in its sole discretion, to modify these Terms and Conditions at any time by posting the modified provisions on the Platform, and Customer shall be responsible for reviewing and becoming familiar with any such modifications. Please note that any such modifications shall become effective immediately upon posting. IF YOU DO NOT AGREE TO ALL OF THESE TERMS AND CONDITIONS, YOU SHOULD NOT USE THE PLATFORM.
          </p>
          <p>
            IF YOU ARE USING THE PLATFORM ON BEHALF OF AN ORGANIZATION, YOU HEREBY DECLARE THAT YOU HAVE THE AUTHORITY OR HAVE BEEN GRANTED APPROVAL BY THE ORGANIZATION TO DO SO AND THAT THE ORGANIZATION IS AWARE OF YOUR ACTIONS AND WILL BE LEGALLY BOUND BY THEM.
          </p>

          <h2>1. The Services</h2>
          <p>
            Company&apos;s Platform is designed to present connectivity data of various communication networks, based on various parameters of communication networks detected through our technology, including their quality of service, reception level, and other traffic characteristics (the &quot;Technology&quot;). Based on sample measurements (the &quot;Sample Data&quot;), the Technology enables the Company to generate predictions for specific area defined by the Customer and evaluate the predicted performance of certain cellular communication networks in this area (the &quot;Polygon Data&quot;). The Company offers the Customer information and analysis based on the Polygon Data generated by the Technology (the &quot;Services&quot;).
          </p>

          <h2>2. Subscription to the Platform</h2>
          <p>
            Subject to the terms and conditions of any order form and/or subscription agreement entered between Customer and Company or Company&apos;s authorized resellers and distributors. Company grants Customer, during the term detailed in the applicable Subscription agreement, a limited, non-exclusive, non-sublicensable, non-transferable right to use the Platform and the Services solely for Customer&apos;s internal business purposes (&quot;Subscription&quot;). The right to use is subject to, and in consideration of, the full payment of the subscription fee for the Platform as set forth in the applicable Subscription agreement.
          </p>

          <h2>3. Customer Data and Responsibilities</h2>

          <h3>3.1. Data</h3>
          <p>
            While using the Platform, Customer may provide, or make accessible to the Company certain non-identifying data, as location information and data related to the electronical devices used by Customer in the framework of the Subscription (&quot;Customer Data&quot;), in addition to data collected and generated independently by Company (&quot;Company Data&quot;, and collectively, the &quot;Data&quot;). Based on such Data, certain analyses and inferences may be generated, based on the parameters and specifications Customer provided to the Company as part of the Subscription, and the Polygon Data.
          </p>

          <h3>3.2. Customer Data; License to Use; Compliance with Applicable Laws</h3>
          <p>
            As between Company and Customer: (i) the Customer Data, and all worldwide intellectual property rights therein, is the exclusive property of Customer, and (ii) the Company Data, and all worldwide intellectual property rights therein is the exclusive property of Company.
          </p>
          <p>
            Customer grants Company a non-exclusive, sublicensable, transferable, worldwide, royalty-free license to process and use the Customer Data as necessary for purposes of providing the Platform and the Services and as otherwise permitted in these Terms and Conditions. Customer warrants that Customer is the owner or legal custodian of, or otherwise has the right and has or will obtain the necessary permissions, valid consents and releases to lawfully transmit, store and use all Customer Data in connection with the Platform and to grant the rights granted to Company under these Terms and Conditions. Notwithstanding anything to the contrary, Customer acknowledges that Company may, at its sole discretion, use the Customer Data and any information and analysis generated in the course of the Services for its own business purposes (including but not limited to re-tagging the Data), provided that in no event shall Customer&apos;s identity be disclosed as result of such use.
          </p>
          <p>
            Customer warrants that it has complied, and will continue to comply, with all applicable laws and regulations applicable to Customer&apos;s use of the Platform including any applicable laws that govern privacy and data protection.
          </p>

          <h3>3.3. Customer Responsibilities for Data and Security</h3>
          <p>
            Customer and its users shall have access to the Customer Data and shall be responsible for all changes to and/or deletions of Customer Data and the security of all passwords and other account information required in order to access and use the Platform. The Customer is encouraged to make his own back-ups of the Data. Customer shall have the sole responsibility for the accuracy, quality, integrity, legality, reliability, and appropriateness of all Customer Data and the means by which Customer acquired Customer Data, and for the adequate security, protection and backup of Customer&apos;s Data. Customer understands that the Platform may store and backup files that are no longer usable due to corruption from viruses, software malfunctions and other causes, which might result in Customer restoring files that are no longer usable.
          </p>

          <h2>4. Restrictions</h2>
          <p>
            Customer must not, and shall not allow any third party to: (i) circumvent, disable or otherwise interfere with features that enforce limitations on use of the Platform; (ii) allow any unauthorized third party to access or use the Platform and/or the Services; (iii) sell, rent, lease, license or timeshare the Platform and/or the Services and/or any information and analysis generated in the course of the Services; (iv) copy, modify, reverse engineer, decompile, disassemble or derive, or attempt to derive, the source code of the Platform; (v) use the Platform or the Services to develop a competing service or product; (vi) interfere or attempt to interfere with the integrity or proper working of the Platform; (vii) access or search the Platform (or download any data or content contained therein or transmitted thereby) through the use of any engine, software, tool, agent, device or mechanism (including spiders, robots, crawlers or any other similar data mining tools) other than software or features provided by Company for use expressly for such purposes; and/or (viii) use or permit or authorize third parties to use the Platform in any way that is defamatory, abusive, harassing, threatening, or otherwise offensive, violent, vulgar, obscene, or otherwise harms or can reasonably be expected to harm any person or entity, or is illegal or encourages or advocates illegal activity, or violates these Terms and Conditions and any applicable local, state, national or international law or regulation.
          </p>

          <h2>5. Title</h2>
          <p>
            The intellectual property rights and all other rights, title and interest of any nature in and to the Platform and the Services, and any related content, documentation and analysis provided or made available by Company hereunder, including all modifications, upgrades, customizations and derivative works of the Platform, are and shall remain the exclusive property of Company and its licensors. Except as expressly set forth herein, nothing in these Terms and Conditions shall be construed as transferring any rights, title or interests to Customer or any third party. The Company and its licensors reserve any and all rights not expressly granted in these Terms and Conditions. In the event that Customer or users on its behalf provide any comments or suggestions in connection with the Platform (&quot;Feedback&quot;), then Company, in its sole discretion, shall be entitled to use the Feedback without restriction, and such Feedback will not be treated as confidential to Customer. Customer hereby grants Company a worldwide, non-exclusive, irrevocable, perpetual, royalty-free right and license to incorporate the Feedback into Company&apos;s products and services.
          </p>

          <h2>6. Suspension</h2>
          <p>
            If Company believes that Customer is using the Platform in a manner that may cause harm to Company or any third party then Company may, without derogating from Company&apos;s right to terminate these Terms and Conditions, suspend Customer&apos;s access to and use of the Platform until such time as Company believes the threat of harm, or actual harm, has passed. In addition, in any event that the Subscription is terminated or terminable by Company or any of its authorized resellers and distributers, Company may immediately terminate Customer&apos;s access to the Platform without any liability to Company.
          </p>

          <h2>7. Termination</h2>
          <p>
            The Company may terminate or suspend the Services (or any part thereof) immediately, without prior notice or liability and on its sole discretion. All the provisions of these Terms and Conditions which by their nature should survive termination (including, without limitation, ownership provisions, warranty disclaimers, indemnification obligations and limitations of liability) shall remain in full force and effect following termination thereof. Termination of these Terms and Conditions shall not relieve Customer from any obligation arising or accruing prior to such termination or limit any liability which Customer otherwise may have toward the Company.
          </p>

          <h2>8. Warranty Disclaimer</h2>
          <p>
            The Services and any information and analysis generated in the course of the Services are based on Sample Data and certain prediction models and are not guaranteed to be 100% accurate. The accuracy of our predictions may be affected by various factors, including (but not limited to) the size of the polygon and the sample measurement data (including the time of the measurement), geographic and/or topographic location, the way and manner by which the Data was collected, weather, network parameters and performance, network traffic type, network traffic load, etc.
          </p>
          <p className="text-xs text-text-muted leading-relaxed uppercase">
            THE PLATFORM AND THE SERVICES ARE PROVIDED ON AN &quot;AS IS&quot; BASIS, AND ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING, WITHOUT LIMITATION, ANY IMPLIED WARRANTY OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, ACCURACY, AVAILABILITY, SECURITY, COMPATIBILITY, NONINFRINGEMENT OR COMPLETENESS OF RESPONSES ARE HEREBY DISCLAIMED TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW. THE COMPANY DOES NOT WARRANT THAT THE USE OF THE PLATFORM WILL BE UNINTERRUPTED, ERROR-FREE OR WILL MEET YOUR SPECIFIC REQUIREMENTS. COMPANY WILL NOT BE LIABLE OR RESPONSIBLE FOR: (A) ANY TECHNICAL PROBLEMS OF THE INTERNET; AND/OR (B) ANY ISSUE THAT IS ATTRIBUTABLE TO CUSTOMER&apos;S SOFTWARE OR CUSTOMER&apos;S INTERNET OR DATA SERVICE PROVIDER.
          </p>

          <h2>9. No Liability for Results and Use; Limitation of Liability</h2>
          <p>
            The use of the Platform by the Customer and on its behalf, and the use of any Data, information, analyses and other data or output generated by the Platform or resulting therefrom, is at the Customer&apos;s sole risk and Customer shall be solely responsible in connection with such use and the results thereof, including but not limited to any decisions based upon interpretations, recommendations, analyses and conclusions derived from such use. The Customer assumes sole and exclusive responsibility for assessing the risks, advantages and consequences of using the Platform, and for all consequences resulting from such use.
          </p>
          <p className="text-xs text-text-muted leading-relaxed uppercase">
            IN NO EVENT WILL COMPANY, ITS SHAREHOLDERS, DIRECTORS, OFFICERS, EMPLOYEES, OR ITS SUPPLIERS BE LIABLE WITH RESPECT TO THE SUBJECT MATTER HEREIN, UNDER ANY LEGAL, CONTRACTUAL OR EQUITABLE THEORY FOR (A) ANY INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES, HOWEVER CAUSED AND WHETHER OR NOT ADVISED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES; (B) DAMAGES FOR LOST PROFITS OR LOST DATA; OR (C) COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY OR SERVICES. IN NO CASE SHALL THE AGGREGATE LIABILITY OF COMPANY EXCEED THE AMOUNT ACTUALLY PAID BY CUSTOMER TO THE COMPANY UNDER THE APPLICABLE SUBSCRIPTION AGREEMENT DURING THE TWELVE (12) MONTHS PRIOR THE OCCURRENCE OF THE ALLEGED DAMAGE.
          </p>

          <h2>10. Confidential Information</h2>
          <p>
            Each Party may have access to certain non-public and/or proprietary information of the other Party, in any form or media, including (without limitation) confidential trade secrets and other information related to the products, software, technology, data, know-how, or business of the other Party (&quot;Confidential Information&quot;). Each Party shall take reasonable measures, at least as protective as those taken to protect its own confidential information, but in no event less than reasonable care, to protect the other Party&apos;s Confidential Information from disclosure to a third party. Neither Party shall use or disclose the Confidential Information of the other Party except as expressly permitted under these Terms and Conditions or by applicable law. All right, title and interest in and to Confidential Information are and shall remain the sole and exclusive property of the disclosing Party.
          </p>

          <h2>11. Indemnification</h2>
          <p>
            Upon its first demand, Customer agrees to defend, indemnify and hold the Company, its shareholders, directors, officers and employees, harmless from any claim, liability, cost, loss, damage and expense (including reasonable legal fees) arising from and/or caused due to: (a) Customer&apos;s use, misuse of, and/or activities in connection with the Platform and the Services; (b) violation of any of these Terms and Conditions or any third party rights, including without limitation privacy right, copyright or any other intellectual property rights of a third party; and (c) any damage of any sort, whether direct, indirect, special or consequential, Customer may cause to any third party with relation to the Services.
          </p>

          <h2>12. Independent Contractors</h2>
          <p>
            The Parties are independent contractors. Nothing in these Terms and Conditions shall create a partnership, joint venture, agency, or employment relationship between the Parties. Neither Party may make, or undertake, any commitments or obligations on behalf of the other.
          </p>

          <h2>13. Assignment</h2>
          <p>
            These Terms and Conditions and any rights or obligations hereunder: (i) may not be transferred or assigned by Customer without the prior written consent of Company which may not be unreasonably withheld; but (ii) may be transferred or assigned by Company. Subject to the foregoing conditions, these Terms and Conditions shall be binding upon and inure to the benefit of each Party and its respective assigns. Any prohibited assignment shall be null and void.
          </p>

          <h2>14. Force Majeure</h2>
          <p>
            Any delay in the performance of any duties or obligations of either Party (except the payment of money owed) will not be considered a breach of these Terms and Conditions if such delay is caused by a labor dispute, shortage of materials, fire, earthquake, flood, endemic, pandemic, or any other event beyond the control of such party, provided that such party uses reasonable efforts, under the circumstances, to notify the other party of the cause of such delay and to resume performance as soon as possible.
          </p>

          <h2>15. Governing Law and Jurisdiction</h2>
          <p>
            These Terms and Conditions and its performance shall be governed exclusively by the laws of the State of Israel, without regard to conflict of laws provisions that may result in the application of the laws of any other jurisdiction. The parties hereto submit the exclusive jurisdiction to the courts of Tel-Aviv-Jaffa.
          </p>

          <h2>16. General</h2>
          <p>
            The headings used in these Terms and Conditions are for convenience only and shall in no case be considered in construing these Terms and Conditions. In the case of an inconsistency or contradiction between these Terms and Conditions and any Subscription, these Terms and Conditions shall prevail. If any part of these Terms and Conditions is held by a court of competent jurisdiction to be illegal or unenforceable, the validity or enforceability of the remainder of these Terms and Conditions shall not be affected and such provision shall be deemed modified to the minimum extent necessary to make such provision consistent with applicable law and, in its modified form, such provision shall then be enforceable and enforced. No failure or delay in exercising any right hereunder by either Party shall operate as a waiver thereof, nor will any partial exercise of any right hereunder preclude further exercise. Each notice and/or demand given by the Company to Customer using the Platform shall be deemed given immediately.
          </p>

          <h2>17. Contact</h2>
          <p>
            If you have any questions or queries about these Terms and Conditions or the Services in general, please do not hesitate to contact us via e-mail at: <a href="mailto:support@flycomm.co" className="text-brand hover:text-brand-light underline underline-offset-2">support@flycomm.co</a>.
          </p>
        </div>
      </div>
    </article>
  );
}
